#/**
# * @author Manvinder Boparai
# * @version 01 Nov 2018
# * @filename change-dns/tasks/fedora.yaml
# *
# * Ansible playbook for updating DNS for fedora based hosts.
# *
# * Copyright 2018 Empowered Networks Inc.
# */

- name: fedora - replace dns address in configuration files
  environment:
    PATH: "{{ hostvars[inventory_hostname]['ansible_facts']['env']['PATH'] }}:/bin:/usr/sbin"
  args:
    executable: /bin/bash
  shell: >
    for file in $(ls /etc/sysconfig/network-scripts/ifcfg-*);
    do
      for res in $(grep 'DNS.*={{from}}' $file);
      do
        dnsNum=$(grep "$res" $file | sed 's/DNS//g' | sed 's/={{from}}//g');
        if [ -n "$dnsNum" ]; then
          sed -i "s/DNS$dnsNum={{from}}$/DNS$dnsNum={{to}}/g" $file;
        fi
      done;
    done;
  register: dns_change_result

#- debug: var=dns_change_result

- name: restart the network service to apply the changes
  become: yes
  async: 60
  poll: 0
  ignore_errors: yes
  retries: 1
  args:
    executable: /bin/bash
  shell: "(sleep 5 && service network restart) &"

- name: wait for the network interface to come back up
  local_action:
    module: wait_for
    host: "{{ ansible_ssh_host }}"
    port: 22
    delay: 10
    state: started
  register: wait_result

- name: refresh network facts
  setup:
    gather_subset: network

- name: display network facts
  debug:
    var: hostvars[inventory_hostname]['ansible_facts']['dns']
