#/**
# * @author Manvinder Boparai
# * @version 01 Nov 2018
# * @filename change-ipv4/tasks/fedora.yaml
# *
# * Ansible playbook for updating IPv4 for fedora based hosts.
# *
# * Copyright 2018 Empowered Networks Inc.
# */

- name: fedora - get interface name where ip address matches
  environment:
    PATH: "{{ hostvars[inventory_hostname]['ansible_facts']['env']['PATH'] }}:/bin:/usr/sbin"
  args:
    executable: /bin/bash
  shell: >
    grep {{from}} /etc/sysconfig/network-scripts/* |
    awk -F':' '{print $1}' |
    sed 's/.*\/ifcfg-//'
  #ip -o -4 a | grep from | awk '{print $2}'
  register: interface_name

- name: replace ip address in configuration file
  become: yes
  replace:
    path: /etc/sysconfig/network-scripts/ifcfg-{{ interface_name.stdout }}
    regexp: IPADDR={{ hostvars[inventory_hostname]["from"] }}$
    replace: IPADDR={{ hostvars[inventory_hostname]["to"] }}

- name: restart the interface to apply the changes
  become: yes
  async: 60
  poll: 0
  ignore_errors: yes
  retries: 1
  args:
    executable: /bin/bash
  shell: "(sleep 5 && ifdown {{ interface_name.stdout }} && ifup {{ interface_name.stdout }}) &"

- name: change ip for ansible
  set_fact:
    ansible_ssh_host: '{{ hostvars[inventory_hostname]["to"] }}'

- name: wait for the network interface to come back up
  local_action:
    module: wait_for
    host: "{{ ansible_ssh_host }}"
    port: 22
    delay: 10
    state: started
  register: wait_result

- name: refresh network facts
  setup:
    gather_subset: network

- name: display network facts
  debug:
    var: hostvars[inventory_hostname]['ansible_facts']['all_ipv4_addresses']


#  handlers:
#    - name: restart network service
#      listen: "interface configuration changed"
#      async: 30
#      poll: 10
#      become: yes
#      service:
#        name: network
#        state: restarted
#
