#/**
# * @author Manvinder Boparai
# * @version 01 Nov 2018
# * @filename change-ipv6/tasks/main.yaml
# *
# * Ansible playbook for updating IPv6 for debian/fedora based hosts.
# *
# * Copyright 2018 Empowered Networks Inc.
# */

- name: run for fedora based distributions - CentOS/RHEL
  import_tasks: roles/change-ipv6/tasks/fedora.yaml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: run for debian based distributions - Ubuntu
  import_tasks: roles/change-ipv6/tasks/debian.yaml
  when: ansible_facts['os_family']|lower == 'debian'